modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="herostand"
version="${mod_version}"
displayName="HeroStand"
description='''Optimized suit displays using non-ticking block entities instead of persistent armor stands.'''

[[dependencies.herostand]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.herostand]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
